name: PaintControlClientServer
description: A sample command-line application.
version: 0.0.1
#homepage: https://www.example.com
#author: kuruma <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  rpc: ^0.5.9
  postgres: ^0.9.9
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0
